# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/chncwang/Documents/Projects/FoolGo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/chncwang/Documents/Projects/FoolGo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.0.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.0.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chncwang/Documents/Projects/FoolGo/CMakeFiles /Users/chncwang/Documents/Projects/FoolGo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chncwang/Documents/Projects/FoolGo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named foolgo

# Build rule for target.
foolgo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 foolgo
.PHONY : foolgo

# fast build rule for target.
foolgo/fast:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/build
.PHONY : foolgo/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/board/board_difference.o: src/board/board_difference.cc.o
.PHONY : src/board/board_difference.o

# target to build an object file
src/board/board_difference.cc.o:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/board_difference.cc.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/board_difference.cc.o
.PHONY : src/board/board_difference.cc.o

src/board/board_difference.i: src/board/board_difference.cc.i
.PHONY : src/board/board_difference.i

# target to preprocess a source file
src/board/board_difference.cc.i:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/board_difference.cc.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/board_difference.cc.i
.PHONY : src/board/board_difference.cc.i

src/board/board_difference.s: src/board/board_difference.cc.s
.PHONY : src/board/board_difference.s

# target to generate assembly for a file
src/board/board_difference.cc.s:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/board_difference.cc.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/board_difference.cc.s
.PHONY : src/board/board_difference.cc.s

src/board/board_output.o: src/board/board_output.cc.o
.PHONY : src/board/board_output.o

# target to build an object file
src/board/board_output.cc.o:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/board_output.cc.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/board_output.cc.o
.PHONY : src/board/board_output.cc.o

src/board/board_output.i: src/board/board_output.cc.i
.PHONY : src/board/board_output.i

# target to preprocess a source file
src/board/board_output.cc.i:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/board_output.cc.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/board_output.cc.i
.PHONY : src/board/board_output.cc.i

src/board/board_output.s: src/board/board_output.cc.s
.PHONY : src/board/board_output.s

# target to generate assembly for a file
src/board/board_output.cc.s:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/board_output.cc.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/board_output.cc.s
.PHONY : src/board/board_output.cc.s

src/board/force.o: src/board/force.cc.o
.PHONY : src/board/force.o

# target to build an object file
src/board/force.cc.o:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/force.cc.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/force.cc.o
.PHONY : src/board/force.cc.o

src/board/force.i: src/board/force.cc.i
.PHONY : src/board/force.i

# target to preprocess a source file
src/board/force.cc.i:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/force.cc.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/force.cc.i
.PHONY : src/board/force.cc.i

src/board/force.s: src/board/force.cc.s
.PHONY : src/board/force.s

# target to generate assembly for a file
src/board/force.cc.s:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/force.cc.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/force.cc.s
.PHONY : src/board/force.cc.s

src/board/position.o: src/board/position.cc.o
.PHONY : src/board/position.o

# target to build an object file
src/board/position.cc.o:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/position.cc.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/position.cc.o
.PHONY : src/board/position.cc.o

src/board/position.i: src/board/position.cc.i
.PHONY : src/board/position.i

# target to preprocess a source file
src/board/position.cc.i:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/position.cc.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/position.cc.i
.PHONY : src/board/position.cc.i

src/board/position.s: src/board/position.cc.s
.PHONY : src/board/position.s

# target to generate assembly for a file
src/board/position.cc.s:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/board/position.cc.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board/position.cc.s
.PHONY : src/board/position.cc.s

src/foolishgo.o: src/foolishgo.cc.o
.PHONY : src/foolishgo.o

# target to build an object file
src/foolishgo.cc.o:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/foolishgo.cc.o
.PHONY : src/foolishgo.cc.o

src/foolishgo.i: src/foolishgo.cc.i
.PHONY : src/foolishgo.i

# target to preprocess a source file
src/foolishgo.cc.i:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/foolishgo.cc.i
.PHONY : src/foolishgo.cc.i

src/foolishgo.s: src/foolishgo.cc.s
.PHONY : src/foolishgo.s

# target to generate assembly for a file
src/foolishgo.cc.s:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/foolishgo.cc.s
.PHONY : src/foolishgo.cc.s

src/math/rand.o: src/math/rand.cc.o
.PHONY : src/math/rand.o

# target to build an object file
src/math/rand.cc.o:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/math/rand.cc.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/math/rand.cc.o
.PHONY : src/math/rand.cc.o

src/math/rand.i: src/math/rand.cc.i
.PHONY : src/math/rand.i

# target to preprocess a source file
src/math/rand.cc.i:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/math/rand.cc.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/math/rand.cc.i
.PHONY : src/math/rand.cc.i

src/math/rand.s: src/math/rand.cc.s
.PHONY : src/math/rand.s

# target to generate assembly for a file
src/math/rand.cc.s:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/math/rand.cc.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/math/rand.cc.s
.PHONY : src/math/rand.cc.s

src/math/vector_util.o: src/math/vector_util.cc.o
.PHONY : src/math/vector_util.o

# target to build an object file
src/math/vector_util.cc.o:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/math/vector_util.cc.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/math/vector_util.cc.o
.PHONY : src/math/vector_util.cc.o

src/math/vector_util.i: src/math/vector_util.cc.i
.PHONY : src/math/vector_util.i

# target to preprocess a source file
src/math/vector_util.cc.i:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/math/vector_util.cc.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/math/vector_util.cc.i
.PHONY : src/math/vector_util.cc.i

src/math/vector_util.s: src/math/vector_util.cc.s
.PHONY : src/math/vector_util.s

# target to generate assembly for a file
src/math/vector_util.cc.s:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/math/vector_util.cc.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/math/vector_util.cc.s
.PHONY : src/math/vector_util.cc.s

src/player/node_record.o: src/player/node_record.cc.o
.PHONY : src/player/node_record.o

# target to build an object file
src/player/node_record.cc.o:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/player/node_record.cc.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/player/node_record.cc.o
.PHONY : src/player/node_record.cc.o

src/player/node_record.i: src/player/node_record.cc.i
.PHONY : src/player/node_record.i

# target to preprocess a source file
src/player/node_record.cc.i:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/player/node_record.cc.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/player/node_record.cc.i
.PHONY : src/player/node_record.cc.i

src/player/node_record.s: src/player/node_record.cc.s
.PHONY : src/player/node_record.s

# target to generate assembly for a file
src/player/node_record.cc.s:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/player/node_record.cc.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/player/node_record.cc.s
.PHONY : src/player/node_record.cc.s

src/util/log_util.o: src/util/log_util.cc.o
.PHONY : src/util/log_util.o

# target to build an object file
src/util/log_util.cc.o:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/util/log_util.cc.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/util/log_util.cc.o
.PHONY : src/util/log_util.cc.o

src/util/log_util.i: src/util/log_util.cc.i
.PHONY : src/util/log_util.i

# target to preprocess a source file
src/util/log_util.cc.i:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/util/log_util.cc.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/util/log_util.cc.i
.PHONY : src/util/log_util.cc.i

src/util/log_util.s: src/util/log_util.cc.s
.PHONY : src/util/log_util.s

# target to generate assembly for a file
src/util/log_util.cc.s:
	$(MAKE) -f CMakeFiles/foolgo.dir/build.make CMakeFiles/foolgo.dir/src/util/log_util.cc.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/util/log_util.cc.s
.PHONY : src/util/log_util.cc.s

test/board/board_TEST.o: test/board/board_TEST.cc.o
.PHONY : test/board/board_TEST.o

# target to build an object file
test/board/board_TEST.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/board/board_TEST.cc.o
.PHONY : test/board/board_TEST.cc.o

test/board/board_TEST.i: test/board/board_TEST.cc.i
.PHONY : test/board/board_TEST.i

# target to preprocess a source file
test/board/board_TEST.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/board/board_TEST.cc.i
.PHONY : test/board/board_TEST.cc.i

test/board/board_TEST.s: test/board/board_TEST.cc.s
.PHONY : test/board/board_TEST.s

# target to generate assembly for a file
test/board/board_TEST.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/board/board_TEST.cc.s
.PHONY : test/board/board_TEST.cc.s

test/board/full_board_TEST.o: test/board/full_board_TEST.cc.o
.PHONY : test/board/full_board_TEST.o

# target to build an object file
test/board/full_board_TEST.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/board/full_board_TEST.cc.o
.PHONY : test/board/full_board_TEST.cc.o

test/board/full_board_TEST.i: test/board/full_board_TEST.cc.i
.PHONY : test/board/full_board_TEST.i

# target to preprocess a source file
test/board/full_board_TEST.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/board/full_board_TEST.cc.i
.PHONY : test/board/full_board_TEST.cc.i

test/board/full_board_TEST.s: test/board/full_board_TEST.cc.s
.PHONY : test/board/full_board_TEST.s

# target to generate assembly for a file
test/board/full_board_TEST.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/board/full_board_TEST.cc.s
.PHONY : test/board/full_board_TEST.cc.s

test/game/monte_carlo_game_TEST.o: test/game/monte_carlo_game_TEST.cc.o
.PHONY : test/game/monte_carlo_game_TEST.o

# target to build an object file
test/game/monte_carlo_game_TEST.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/game/monte_carlo_game_TEST.cc.o
.PHONY : test/game/monte_carlo_game_TEST.cc.o

test/game/monte_carlo_game_TEST.i: test/game/monte_carlo_game_TEST.cc.i
.PHONY : test/game/monte_carlo_game_TEST.i

# target to preprocess a source file
test/game/monte_carlo_game_TEST.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/game/monte_carlo_game_TEST.cc.i
.PHONY : test/game/monte_carlo_game_TEST.cc.i

test/game/monte_carlo_game_TEST.s: test/game/monte_carlo_game_TEST.cc.s
.PHONY : test/game/monte_carlo_game_TEST.s

# target to generate assembly for a file
test/game/monte_carlo_game_TEST.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/game/monte_carlo_game_TEST.cc.s
.PHONY : test/game/monte_carlo_game_TEST.cc.s

usr/share/gtest-1.7.0/src/gtest_main.o: usr/share/gtest-1.7.0/src/gtest_main.cc.o
.PHONY : usr/share/gtest-1.7.0/src/gtest_main.o

# target to build an object file
usr/share/gtest-1.7.0/src/gtest_main.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/usr/share/gtest-1.7.0/src/gtest_main.cc.o
.PHONY : usr/share/gtest-1.7.0/src/gtest_main.cc.o

usr/share/gtest-1.7.0/src/gtest_main.i: usr/share/gtest-1.7.0/src/gtest_main.cc.i
.PHONY : usr/share/gtest-1.7.0/src/gtest_main.i

# target to preprocess a source file
usr/share/gtest-1.7.0/src/gtest_main.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/usr/share/gtest-1.7.0/src/gtest_main.cc.i
.PHONY : usr/share/gtest-1.7.0/src/gtest_main.cc.i

usr/share/gtest-1.7.0/src/gtest_main.s: usr/share/gtest-1.7.0/src/gtest_main.cc.s
.PHONY : usr/share/gtest-1.7.0/src/gtest_main.s

# target to generate assembly for a file
usr/share/gtest-1.7.0/src/gtest_main.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/usr/share/gtest-1.7.0/src/gtest_main.cc.s
.PHONY : usr/share/gtest-1.7.0/src/gtest_main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... foolgo"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... tests"
	@echo "... src/board/board_difference.o"
	@echo "... src/board/board_difference.i"
	@echo "... src/board/board_difference.s"
	@echo "... src/board/board_output.o"
	@echo "... src/board/board_output.i"
	@echo "... src/board/board_output.s"
	@echo "... src/board/force.o"
	@echo "... src/board/force.i"
	@echo "... src/board/force.s"
	@echo "... src/board/position.o"
	@echo "... src/board/position.i"
	@echo "... src/board/position.s"
	@echo "... src/foolishgo.o"
	@echo "... src/foolishgo.i"
	@echo "... src/foolishgo.s"
	@echo "... src/math/rand.o"
	@echo "... src/math/rand.i"
	@echo "... src/math/rand.s"
	@echo "... src/math/vector_util.o"
	@echo "... src/math/vector_util.i"
	@echo "... src/math/vector_util.s"
	@echo "... src/player/node_record.o"
	@echo "... src/player/node_record.i"
	@echo "... src/player/node_record.s"
	@echo "... src/util/log_util.o"
	@echo "... src/util/log_util.i"
	@echo "... src/util/log_util.s"
	@echo "... test/board/board_TEST.o"
	@echo "... test/board/board_TEST.i"
	@echo "... test/board/board_TEST.s"
	@echo "... test/board/full_board_TEST.o"
	@echo "... test/board/full_board_TEST.i"
	@echo "... test/board/full_board_TEST.s"
	@echo "... test/game/monte_carlo_game_TEST.o"
	@echo "... test/game/monte_carlo_game_TEST.i"
	@echo "... test/game/monte_carlo_game_TEST.s"
	@echo "... usr/share/gtest-1.7.0/src/gtest_main.o"
	@echo "... usr/share/gtest-1.7.0/src/gtest_main.i"
	@echo "... usr/share/gtest-1.7.0/src/gtest_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

